### ISSUE TITLE
What is the need for t_final in solver objects?

### ISSUE THREAD

**Issue by aarchiba** [drhagen/scipy_ode#2]
When a solver object is constructed, the user must provide a number t_final. This is used to define the solver's direction, but users - particularly users using bare solver objects - may not know a final value of the interval; they may be planning to stop when an event occurs or when the solution covers all the yet-to-be-provided data. I suppose users can supply np.inf or -np.inf, but why not simply allow them to specify a solver direction directly?

**Comment by drhagen** [comment]
The purpose of `t_final` is to define the analytic boundary of `fun`. It is just a bonus that it also defines the direction. Many ODE solvers will crash if they encounter a discontinuity in `fun`. All ODE solvers with tolerances are written with the assumption that `fun` is analytic. Without this parameter, there is no way to integrate up to a boundary without stepping over it.

I am open to alternative names, like `t_bound`, `tF`, etc.

**Comment by aarchiba** [comment]
This is usually called t_crit. But I think it is more properly an optional argument to `step`: for some singularities it may be possible to continue after reaching such a point, while for other problems there may be no natural candidate for t_crit. To be honest I have never integrated a problem where the singularities were identifiable purely in terms of t; they have always depended on y values.

Supplying `t_crit` as an option to `step` also allows an easy implementation: enforce a maximum step size that ends at `t_crit`.

**Comment by drhagen** [comment]
> This is usually called t_crit.

Perfect.

> To be honest I have never integrated a problem where the singularities were identifiable purely in terms of t; they have always depended on y values.

All my work is the complete opposite. It feels like your work requires a way to find `y` dependent discontinuities. Is this something other than applying terminal events and starting a new integration?

> Supplying t_crit as an option to step also allows an easy implementation: enforce a maximum step size that ends at t_crit.

What would `solve_ivp` provide to this in its call to `step`?

**Comment by aarchiba** [comment]
> > To be honest I have never integrated a problem where the singularities were identifiable purely in terms of t; they have always depended on y values.

> All my work is the complete opposite. It feels like your work requires a way to find y dependent discontinuities. Is this something other than applying terminal events and starting a new integration?

Good that we have people with different experience to shape the design! At some point, maybe once we have a decent-looking setup, it may make sense to pass it around the mailing list and call for more different experiences.

The black-hole ray-tracer just needed the solver to stop gracefully somewhere nearby when it crashed into the singularities. I tried using event detection to stop it away from the singularity, but it was a fairly smooth system so the solvers tended to take large steps and they would sometimes hit the singularity in the same step where they crossed the event.

More generally, if the solution encounters a singularity the user is going to need to step in and do something clever (probably based on an understanding of the system). But often the user is only interested in a solution that doesn't go anywhere near the singularity. In this case, if the solver finds itself evaluating in a singular region, it should back off and take smaller steps. If the singular region can't be avoided, it's time to drop back to the user and let them deal with it.

> > Supplying t_crit as an option to step also allows an easy implementation: enforce a maximum step size that ends at t_crit.

> What would solve_ivp provide to this in its call to step?

I would say that solve_ivp should take an array of points `t_crit` that are known to be trouble. They'd be sorted, and each time a step was taken, it would be provided with the next `t_crit` value in the direction it was going. If `solve_ivp` is provided with an interval, it may make sense to treat the endpoint of the interval as a `t_crit` value. (I favour a `solve_ivp_lazy` implementation. But the same might be done for `solve_ivp_discrete`.) Steps should not be shortened to stop at every goal point, because for high-order solvers that can take large steps this is inefficient and throws off adaptive step-size and order control for the next steps, but treating the last evaluation point as suspect doesn't hurt much.
