### ISSUE TITLE
Order of parameters in signature

### ISSUE THREAD

**Issue by drhagen** [drhagen/scipy_ode#4]
I am thinking about what the signature of `solve_ivp` should be:

* `solve_ivp((t0,tF), y0, fun, ...)`: This was how @nmayorov had it initially. It is also how Matlab does it.

* `solve_ivp(t0, tF, y0, fun, ...)`: This is simply the signature above, but with the tuple unpacked. This is how it is right now.

* `solve_ivp(fun, y0, t0, tF, ...)`: This is most similar to the signature of similar methods in scipy
    * `minimize(fun, x0, ...)`
    * `solve_bvp(fun, bc, x, y, ...)`
    * `quadrature(fun, a, b, ...)`

* `solve_ivp(fun, y0, (t0, tF), ...)`: Like the one above but with a tuple

I am inclined to use the signature most like the other functions in scipy. At first I thought it was a little backwards (probably because of my experience with Matlab), but now I am starting to like it. Whatever is done, I think the signatures of the solvers should be changed to match.

The advantage of a tuple is that it allows the signature to also accept a scalar, which would be interpreted as `tF` with a `t0=0`. I don't think this is worth the complication of the signature. Even though almost everyone will have `t0=0`, it's not that much typing.

**Comment by nmayorov** [comment]
And I agree with you. Let's go with `solve_ivp(fun, y0, t0, tF)`.

**Comment by aarchiba** [comment]
I would still like to argue for dropping tF entirely (the `solve_ivp_lazy` approach). But I think the thing to do is for me to supply a `solve_ivp_lazy` implementation in a pull request and try to convince you that it's a convenient interface.

I do have one concern, though, and it's actually what is driving this whole ODE rewrite: what is the correct order of `t` and `y`?  As it stands `fun` gets called as `fun(t,y)`. If that's how we're calling `fun`, I think `t` should precede `y` in other call signatures as well, as universally as we can manage it.
