### ISSUE TITLE
This repository form

### ISSUE THREAD

**Issue by nmayorov** [drhagen/scipy_ode#5]
It's not very important. But I suggest to put this repository in a more convenient and straightforward form:

```
scipy_ode/
  tests/
  __init__.py
  other source files
README.md
.gitignore
```

It will be self-contained repository without awkward legacy from scipy.integrate. After it's finished it will be very easy to include it back to scipy.integrate.

**Comment by drhagen** [comment]
Right now the bulk of the code is in `_py`. Do you want `scipy_ode/_py/rk.py` or `scipy_ode/rk.py`? This will affect how `__init__.py` is written.

**Comment by nmayorov** [comment]
I think the simplest way is just scipy_ode/rk.py, etc.
