### ISSUE TITLE
Indexing support in OdeSolution produces VisibleDeprecationWarnings

### ISSUE THREAD

**Issue by aarchiba** [drhagen/scipy_ode#8]
The test suite produces many instances of:
```
/home/archibald/projects/scipy_ode/scipy_ode/scipy_ode/ivp.py:222: VisibleDeprecationWarning: an index can only have a single Ellipsis (`...`); replace all but one with slices (`:`).
  return result[..., iy]
```

I don't think there's any need for OdeSolution to index the solution object at all; simply use `return result` and users can do any indexing they feel they need.

**Comment by drhagen** [comment]
What version of Python and Scipy are you running? I don't get any of these on Python 3.5.2 with Scipy 0.17.0. There are a lot of ways to fix this, but removing the functionality may be best.

**Comment by aarchiba** [comment]
With python 2.7.12, numpy 1.11.0, scipy 0.17, and nosetests 1.3.7 I get the warning once. With python 3.5.2,  numpy 1.11.1, scipy 0.17.0, and nosetests 1.3.7 I get the warning repeatedly, once per use. (I'm guessing that's from an improvement in warnings support in python3; test suites can have trouble triggering warnings repeatedly in python2.) But the fact is that indexing with more than one ellipsis is trouble in all versions of numpy; there's a very slow deprecation cycle but it will turn into an error in a few versions.
